import express from "express";
import { register, verifyOTP, login, me, resendOTP } from "../controllers/authController.js";
import { requireAuth } from "../middleware/auth.js";
const router = express.Router();
router.post("/register", register);
router.post("/verify-otp", verifyOTP);
router.post("/resend-otp", resendOTP);
router.post("/login", login);
router.get("/me", requireAuth, me);
export default router;
