import { useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { Search, SlidersHorizontal, MapPin, CalendarDays, Sparkles, RotateCcw, X } from "lucide-react";
import { fetchCommunityItems, findMatchesFor } from "../utils/lostFound";

function ItemCard({ item, onMatch }) {
 const path=item.source==="static"?`/item/${item.id}`:item.status==="Lost"?`/lost-report/${item.id}`:`/found-report/${item.id}`;
 return <article className="group overflow-hidden rounded-2xl border bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-[4/3] bg-slate-100">{item.image?<img src={item.image} alt={item.name} className="h-full w-full object-cover transition group-hover:scale-105"/>:<div className="grid h-full place-items-center text-5xl">📦</div>}<span className={`absolute left-3 top-3 rounded-full px-3 py-1 text-xs font-bold ${item.status==="Lost"?"bg-red-100 text-red-700":"bg-emerald-100 text-emerald-700"}`}>{item.status}</span></div><div className="p-5"><div className="flex items-start justify-between gap-3"><h3 className="line-clamp-1 text-lg font-black">{item.name}</h3><span className="rounded-lg bg-slate-100 px-2 py-1 text-xs text-slate-600">{item.category}</span></div><p className="mt-2 line-clamp-2 text-sm text-slate-500">{item.description}</p><div className="mt-4 space-y-2 text-sm text-slate-600"><p className="flex gap-2"><MapPin size={16}/>{item.location}{item.city?`, ${item.city}`:""}</p><p className="flex gap-2"><CalendarDays size={16}/>{item.date||"Date not provided"}</p></div><div className="mt-5 grid grid-cols-2 gap-2"><Link to={path} className="rounded-xl bg-slate-900 px-3 py-2.5 text-center text-sm font-bold text-white">View item</Link><button onClick={()=>onMatch(item)} className="rounded-xl bg-blue-50 px-3 py-2.5 text-sm font-bold text-blue-700">Find match</button></div></div></article>
}

export default function ItemBrowser({status}){
 const [params,setParams]=useSearchParams(); const [all,setAll]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const [search,setSearch]=useState(params.get("q")||""); const [category,setCategory]=useState(params.get("category")||"All"); const [city,setCity]=useState(params.get("city")||"All"); const [location,setLocation]=useState(params.get("location")||"All"); const [sort,setSort]=useState("newest"); const [matchFor,setMatchFor]=useState(null);
 useEffect(()=>{fetchCommunityItems().then(setAll).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const pool=useMemo(()=>all.filter(x=>x.status===status),[all,status]);
 const categories=["All",...new Set(pool.map(x=>x.category).filter(Boolean))]; const cities=["All",...new Set(pool.map(x=>x.city).filter(Boolean).sort())]; const locations=["All",...new Set(pool.map(x=>x.location).filter(Boolean).sort())];
 const items=useMemo(()=>{let r=pool;const q=search.toLowerCase().trim();if(q)r=r.filter(x=>`${x.name} ${x.category} ${x.location} ${x.city} ${x.description} ${x.color} ${x.brand}`.toLowerCase().includes(q));if(category!=="All")r=r.filter(x=>x.category===category);if(city!=="All")r=r.filter(x=>x.city===city);if(location!=="All")r=r.filter(x=>x.location===location);return [...r].sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):sort==="oldest"?new Date(a.date)-new Date(b.date):new Date(b.date)-new Date(a.date))},[pool,search,category,city,location,sort]);
 const reset=()=>{setSearch("");setCategory("All");setCity("All");setLocation("All");setSort("newest");setParams({});};
 return <main className="min-h-screen bg-slate-50 px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><header className="rounded-3xl bg-gradient-to-br from-slate-900 via-blue-950 to-indigo-900 p-6 text-white shadow-xl sm:p-10"><span className={`rounded-full px-3 py-1 text-xs font-bold ${status==="Lost"?"bg-red-500/20 text-red-200":"bg-emerald-500/20 text-emerald-200"}`}>{status.toUpperCase()} ITEMS</span><h1 className="mt-4 text-3xl font-black sm:text-5xl">{status==="Lost"?"Find what was lost.":"Help return what was found."}</h1><p className="mt-3 max-w-2xl text-sm text-slate-300">Real community reports plus the existing demo catalog. Filter by category, city and exact location.</p></header>
 <section className="sticky top-[76px] z-20 mt-5 rounded-2xl border bg-white/95 p-3 shadow-lg backdrop-blur sm:p-4"><div className="grid gap-3 lg:grid-cols-[1.5fr_repeat(4,1fr)_auto]"><label className="relative"><Search className="absolute left-4 top-3.5 text-slate-400" size={20}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search item, brand, color…" className="h-12 w-full rounded-xl border bg-slate-50 pl-11 pr-4 outline-none focus:ring-4 focus:ring-blue-100"/></label><select value={category} onChange={e=>setCategory(e.target.value)} className="h-12 rounded-xl border px-3"><option>All</option>{categories.slice(1).map(x=><option key={x}>{x}</option>)}</select><select value={city} onChange={e=>setCity(e.target.value)} className="h-12 rounded-xl border px-3"><option>All</option>{cities.slice(1).map(x=><option key={x}>{x}</option>)}</select><select value={location} onChange={e=>setLocation(e.target.value)} className="h-12 rounded-xl border px-3"><option>All locations</option>{locations.slice(1).map(x=><option key={x}>{x}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)} className="h-12 rounded-xl border px-3"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="name">Name A-Z</option></select><button onClick={reset} className="flex h-12 items-center justify-center gap-2 rounded-xl bg-slate-100 px-4 font-bold"><RotateCcw size={16}/>Reset</button></div><div className="mt-3 flex items-center gap-2 text-sm text-slate-500"><SlidersHorizontal size={16}/><b className="text-slate-900">{items.length}</b> {status.toLowerCase()} reports · <b className="text-slate-900">{cities.length-1}</b> cities · <b className="text-slate-900">{locations.length-1}</b> locations</div></section>
 {error&&<div className="mt-6 rounded-xl bg-red-50 p-4 font-semibold text-red-700">{error}</div>}{loading?<div className="py-20 text-center font-semibold text-slate-500">Loading real reports…</div>:items.length?<div className="mt-7 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{items.map(item=><ItemCard key={`${item.source}-${item.id}`} item={item} onMatch={setMatchFor}/>)}</div>:<div className="mt-8 rounded-2xl border-dashed border bg-white p-12 text-center"><Search className="mx-auto text-slate-300" size={42}/><h2 className="mt-4 text-xl font-bold">No reports found</h2><p className="mt-2 text-slate-500">Try another category, city, location or keyword.</p></div>}
 {matchFor&&<MatchPanel item={matchFor} all={all} onClose={()=>setMatchFor(null)}/>}</div></main>
}
function MatchPanel({item,all,onClose}){const matches=findMatchesFor(item,all,35).slice(0,8);const [selected,setSelected]=useState(matches[0]||null);return <div className="fixed inset-0 z-[70] flex items-end justify-center bg-slate-950/70 sm:items-center sm:p-6" onClick={onClose}><div onClick={e=>e.stopPropagation()} className="max-h-[92vh] w-full max-w-5xl overflow-y-auto rounded-t-3xl bg-white p-5 shadow-2xl sm:rounded-3xl sm:p-7"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-blue-600"><Sparkles size={18}/><span className="text-sm font-bold">MATCH CENTER</span></div><h2 className="mt-1 text-2xl font-black">{item.name} → possible {item.status==="Lost"?"found":"lost"} items</h2></div><button onClick={onClose} className="rounded-full bg-slate-100 p-2"><X/></button></div>{!matches.length?<p className="py-12 text-center text-slate-500">No matching report yet.</p>:<><div className="mt-5 grid gap-3 sm:grid-cols-2">{matches.map(m=><button key={`${m.source}-${m.id}`} onClick={()=>setSelected(m)} className={`rounded-2xl border p-4 text-left ${selected?.id===m.id?"border-blue-500 bg-blue-50":"hover:bg-slate-50"}`}><div className="flex items-center justify-between gap-3"><div><p className="font-black">{m.name}</p><p className="text-sm text-slate-500">{m.location}, {m.city}</p></div><b className="rounded-full bg-emerald-100 px-3 py-1 text-emerald-700">{m.score}%</b></div><div className="mt-2 flex flex-wrap gap-2">{m.reasons.map(r=><span key={r} className="rounded-full bg-white px-2 py-1 text-xs text-slate-600">{r}</span>)}</div></button>)}</div>{selected&&<Compare lost={item.status==="Lost"?item:selected} found={item.status==="Lost"?selected:item}/>}</>}</div></div>}
function Compare({lost,found}){const rows=[['Item',lost.name,found.name],['Category',lost.category,found.category],['Location',`${lost.location}${lost.city?`, ${lost.city}`:""}`,`${found.location}${found.city?`, ${found.city}`:""}`],['Date',lost.date,found.date],['Color',lost.color||'Not provided',found.color||'Not provided'],['Brand',lost.brand||'Not provided',found.brand||'Not provided'],['Description',lost.description,found.description]];return <div className="mt-6 overflow-hidden rounded-2xl border"><div className="grid grid-cols-2 bg-slate-900 text-white sm:grid-cols-3"><div className="hidden p-4 font-bold sm:block">Field</div><div className="p-4 font-bold">🔴 Lost</div><div className="p-4 font-bold">🟢 Found</div></div>{rows.map(([a,b,c])=><div key={a} className="grid grid-cols-2 border-t sm:grid-cols-3"><div className="hidden bg-slate-50 p-4 text-sm font-bold sm:block">{a}</div><div className="p-4 text-sm"><span className="mb-1 block text-xs font-bold text-slate-400 sm:hidden">{a}</span>{b}</div><div className="border-l p-4 text-sm"><span className="mb-1 block text-xs font-bold text-slate-400 sm:hidden">{a}</span>{c}</div></div>)}</div>}
